# Project information
site_name: 'Select Documentation'
site_description: 'Building blocks for common selection user interfaces in PureScript & Halogen'
site_author: 'Thomas Honeyman'
site_url: 'https://citizennet.github.io/purescript-halogen-select'

# Repository
repo_name: 'purescript-halogen-select'
repo_url: 'https://github.com/citizennet/purescript-halogen-select'

# Copyright
copyright: 'Copyright &copy; 2018 CitizenNet'

# Config
theme:
  name: 'material'
  custom_dir: 'docs/theme'
  language: 'en'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo:
    icon: 'school'

# To mount components
extra_javascript:
  - js/app.js

# To style components
# extra_css:
#   - css/cn-tailwind.scoped.css

# Google Analytics
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'

# Extensions
# Recommended here:
# https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Site architecture
pages:
  - Home: 'index.md'
  # - Tutorials:
  #   - 'Dropdown': 'tutorials/dropdown.md'
  #   - 'Typeahead': 'tutorials/typeahead.md'
  #   - 'Date Picker': 'tutorials/date-picker.md'
  # - About:
  #   - 'Design Philosophy': 'about/design-philosophy.md'
  #   - 'Talks': 'about/talks.md'
  # - Reference: 'reference.md'
